### ISSUE TITLE
Use dat-dns to process feeds file

### ISSUE THREAD

**Issue by millette** [jimpick/subscribed-hypercored#1]
Would you accept a patch similar to <https://github.com/mafintosh/hypercored/pull/1> to handle dns names in the feeds file?

**Comment by jimpick** [comment]
For sure! (sorry for the delay, i missed the email somehow)

**Comment by jimpick** [comment]
Also, it looks like it was merged upstream ... I should probably sync up.

**Comment by jimpick** [comment]
I've updated the code to use dat-dns and synced the code up to 1.3.0.
